#pragma once

#include "Patches.h"

#define ALLOWED_WILDCARD_DOMAINS "rbxcdn.com", "roblox.com"
#define ALLOWED_DOMAINS
#define ALLOWED_SCHEMES "http", "https"
#define ALLOWED_EMBEDDED_SCHEMES "javascript", "jscript", "res"
#define PUBLIC_KEY "BgIAAACkAABSU0ExAAQAAAEAAQCjbUyx9OXTBcWEAonZOfAoT7YhMS+L21WwAZlsEjvzHXQpulpasNFhC1U6tBX6c8Qey2fiRBXHpqbh7vAC7u2niT6dMLLqY9UzII0jyxKD/EUODcQHTKpbM18FRobqLcvK0DNdIaHwypr7NRnSWk4NXhtM0v40W7/mr35PxbJ8rQ=="
// #define RESOLVE_OFFSETS

#define MFC2010

// RobloxApp (2010)
#ifdef MFC2010

#define ADDRESS_CONTEXT__REQUIREPERMISSION   LOCATION(0x004A2360)
#define ADDRESS_CONTEXT__ISINROLE            LOCATION(0x0065E550)
#define ADDRESS_CRYPT__VERIFYSIGNATUREBASE64 LOCATION(0x0079ECF0)
#define ADDRESS_GAME__CONSTRUCT              LOCATION(0x0047DBF0)
#define ADDRESS_HTTP__HTTPGETPOSTWININET     LOCATION(0x006A9210)
#define ADDRESS_HTTP__TRUSTCHECK             LOCATION(0x005A2680)

#endif